# Generated by Django 5.2 on 2025-11-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['created_at'], name='leave_reque_created_08d1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'created_at'], name='leave_reque_employe_e0c7d1_idx'),
        ),
    ]
